elasticsearch:
  replicas: 3
  image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
  resources:
    limits:
      cpu: "2"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "4Gi"
  storage:
    size: 50Gi
    storageClassName: nfs-storageclass
  password: changeme

kibana:
  replicas: 1
  image: docker.elastic.co/kibana/kibana:8.5.0
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  storage:
    size: 50Gi
    storageClassName: nfs-storageclass
  pluginsStorage:
    size: 5Gi
    storageClassName: nfs-storageclass
  elasticsearchPassword: changeme
