apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
stringData:
  api-token: "ujNxiS7EDU_B0hUHbtPU2UuDJnYWtDHzX1s8PcRN"
# 创建CF API密钥的Secret对象，用于访问Cloudflare API
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: imfx003@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - dns01:
        cloudflare:
          email: imfx003@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
