apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pt-dev
spec:
  type: LoadBalancer
  loadBalancersourceRanges:
  - 1.1.1.1/32
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis