---
apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  namespace: pt-dev
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 83.110.183.32/32
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mysql8
    app.kubernetes.io/name: mysql
