apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: pt-dev
  name: mysql-server
  labels:
    app: mysql-server-sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  serviceName: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: mysql:8.0.19
          name: mysql-server
          args:
            - "--default-authentication-plugin=mysql_native_password"
            - --character-set-server=utf8
            - --collation-server=utf8_bin
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: zabbix-app
                  
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key:  MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key:  MYSQL_PASSWORD
           
          ports:
            - containerPort: 3306
              name: mysql-server
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

# ---
# # kind: StorageClass
# # apiVersion: storage.k8s.io/v1
# # metadata:
# #   name: manual
# #   namespace: devops-test
# # provisioner: docker.io/hostpath
# # reclaimPolicy: Retain

---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: pt-dev
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql-server
spec:
  storageClassName: csi-disk-topology
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pt-dev
  name: mysql-pv-claim
  labels:
    app: mysql-server
spec:
  storageClassName: csi-disk-topology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: pt-dev
  name: mysql-server
  labels:
    app: mysql-server
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-server

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: pt-dev
  name: zabbix-app
  labels:
    app: mysql-server
data:
  MYSQL_DATABASE: "nacos"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: pt-dev
  name: zabbix-app
  labels:
    app: mysql-server
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eUNURlJBVHJ0WDNHVTM=
  MYSQL_USER: bmFjb3M=
  MYSQL_PASSWORD: eUNURlJBVHJ0WDNHVTM=
