apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: pt-dev
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mysql8
    app.kubernetes.io/name: mysql
  clusterIP: None