apiVersion: v1
kind: persistentVolume
metadata:
  name: zentao
  labels:
    app: zentao
  namespace: zentao
spec:
  resources::
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs-storageclass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zentao
  name: zentao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentao
  template:
    metadata:
      labels:
        app: zentao
    spec:
      containers:
      - env:
        - name: MYSQL_INTERNAL
          value: "true"
        image: hub.zentao.net/app/zentao:18.8
        imagePullPolicy: Always
        name: zentao
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: zentao
          mountPath: /data
      volumes:
      - name: zentao
        nfs:
          server: 192.168.3.61
          path: /zentao
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: zentao
  name: zentao-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: zentao
  type: ClusterIP

 