apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: zentao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: zentao-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zentao
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
