apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentao
  namespace: zentao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentao
  template:
    metadata:
      labels:
        app: zentao
    spec:
      initContainers:
        - name: init-zentao
          image: easysoft/zentao:21.4
          command: ["sh", "-c", "cp -r /opt/zbox/* /opt/zbox-data"]
          volumeMounts:
            - name: zentao-data
              mountPath: /opt/zbox
      containers:
        - name: zentao
          image: easysoft/zentao:21.4
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "zentao"
            - name: MYSQL_PASSWORD
              value: "zentao123123"
            - name: MYSQL_DATABASE
              value: "zentao"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: zentao-data
              mountPath: /opt/zbox
      volumes:
        - name: zentao-data
          persistentVolumeClaim:
            claimName: zentao-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zentao
  namespace: zentao
spec:
  selector:
    app: zentao
  ports:
    - port: 80
      targetPort: 80
