apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: es
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: "${NODE_NAME}"
      hosts: ["https://${NODE_NAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - uptime
      processors:
      - drop_event.when.regexp:
          system.process.cmdline: '.*(docker|containerd).*'

    output.elasticsearch:
      hosts: ['http://elasticsearch:9200']
      username: elastic
      password: aGlE3w56z0abFNFflIs5
