apiVersion: v1
kind: ConfigMap
metadata:
  name: pt-game-bet-settled-record
  namespace: es
data:
  pt-settled-record.yml: |
    dataSourceKey: gameDS
    destination: mysql8-to-es-pt-game
    groupId: g1
    outerAdapterKey: es
    esMapping:
      _index: ga_settled_record
      _type: _doc
      _id: id
      pk: id
      upsert: true
      sql: "
        SELECT
          id,
          settled_no,
          bet_no,
          third_transaction_id,
          COALESCE(third_external_transaction_id, '') as third_external_transaction_id,
          third_currency,
          third_currency_rate,
          third_currency_type,
          exchange_rate,
          COALESCE(third_win_amount, 0) as third_win_amount,
          third_round_id,
          third_bet_id,
          COALESCE(win_amount, 0) as win_amount,
          wallet_currency,
          wallet_currency_rate,
          wallet_currency_type,
          DATE_FORMAT(COALESCE(settled_time, NOW()), '%Y-%m-%d %H:%i:%s') as settled_time
        FROM
          ga_settled_record t
      "
      commitBatch: 1000