apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-adapter-config
  namespace: es
data:
  application.yml: |
    server:
      port: 8081
    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    canal.conf:
      mode: tcp
      flatMessage: true
      zookeeperHosts:
      syncBatchSize: 1000
      retries: -1
      timeout:
      accessKey:
      secretKey:
      consumerProperties:
        canal.tcp.server.host: canal-server-headless.es.svc.cluster.local:11111
        canal.tcp.zookeeper.hosts:
        canal.tcp.batch.size: 500
        canal.tcp.username:
        canal.tcp.password:
      srcDataSources:
        defaultDS:
          url: jdbc:mysql://15e054ac55e349438b27783e7ca0ff95in01.internal.ap-southeast-3.mysql.rds.myhuaweicloud.com:3306/pt-member?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: yCCTFRdkfTFRdkfuwioaly
          driverClassName: com.mysql.cj.jdbc.Driver
          maxActive: 10
          initialSize: 2
          minIdle: 1
          maxWait: 60000
          useUnfairLock: true
          validationQuery: SELECT 1
          testOnBorrow: true
          testWhileIdle: true
        gameDS:
          url: jdbc:mysql://15e054ac55e349438b27783e7ca0ff95in01.internal.ap-southeast-3.mysql.rds.myhuaweicloud.com:3306/pt-game?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: q&2Lys%ygkhZ3wy
          driverClassName: com.mysql.cj.jdbc.Driver
          maxActive: 10
          initialSize: 2
          minIdle: 1
          maxWait: 60000
          useUnfairLock: true
          validationQuery: SELECT 1
          testOnBorrow: true
          testWhileIdle: true
        activityDS:
          url: jdbc:mysql://15e054ac55e349438b27783e7ca0ff95in01.internal.ap-southeast-3.mysql.rds.myhuaweicloud.com:3306/pt-activity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
          username: root
          password: q&2Lys%ygkhZ3wy
          driverClassName: com.mysql.cj.jdbc.Driver
          maxActive: 10
          initialSize: 2
          minIdle: 1
          maxWait: 60000
          useUnfairLock: true
          validationQuery: SELECT 1
          testOnBorrow: true
          testWhileIdle: true
      canalAdapters:
      - instance: mysql8-to-es-pt-member
        groups:
        - groupId: g1
          outerAdapters:
          - name: logger
          - name: es7
            key: es
            hosts: 192.168.0.191:9200
            properties:
              mode: rest
              type: _doc
              # security.auth: elastic:aGlE3w56z0abFNFflIs5
              cluster.name: pt-pre-es2
      - instance: mysql8-to-es-pt-game
        groups:
        - groupId: g1
          outerAdapters:
          - name: logger
          - name: es7
            key: es
            hosts: 192.168.0.191:9200
            properties:
              mode: rest
              type: _doc
              # security.auth: elastic:aGlE3w56z0abFNFflIs5
              cluster.name: pt-pre-es2
      - instance: mysql8-to-es-pt-activity
        groups:
        - groupId: g1
          outerAdapters:
          - name: logger
          - name: es7
            key: es
            hosts: 192.168.0.191:9200
            properties:
              mode: rest
              type: _doc
              # security.auth: elastic:aGlE3w56z0abFNFflIs5
              cluster.name: pt-pre-es2

