apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-adapter-config-es
  namespace: es
data:
  pt-member.yml: |
    dataSourceKey: defaultDS
    destination: mysql8-to-es-pt-member
    groupId: g1
    outerAdapterKey: es
    esMapping:
      _index: mem_account_change
      _type: _doc
      _id: id
      upsert: true
      sql: "SELECT id, user_no, account_type, source_currency, source_amount, exchange_rate, currency_type, currency, change_amount, before_amount, after_amount, agent_id, channel_id, transaction_no, income_type, main_change_type, sub_change_type, third_main_transaction_no, third_sub_transaction_no, remark, create_time, update_time FROM mem_account_change"
      commitBatch: 1
      fieldMapping:
        id: {name: id, type: long}
        user_no: {name: user_no, type: integer}
        account_type: {name: account_type, type: integer}
        source_currency: {name: source_currency, type: keyword}
        source_amount: {name: source_amount, type: double}
        exchange_rate: {name: exchange_rate, type: double}
        currency_type: {name: currency_type, type: integer}
        currency: {name: currency, type: keyword}
        change_amount: {name: change_amount, type: double}
        before_amount: {name: before_amount, type: double}
        after_amount: {name: after_amount, type: double}
        agent_id: {name: agent_id, type: integer}
        channel_id: {name: channel_id, type: integer}
        transaction_no: {name: transaction_no, type: long}
        income_type: {name: income_type, type: integer}
        main_change_type: {name: main_change_type, type: integer}
        sub_change_type: {name: sub_change_type, type: integer}
        third_main_transaction_no: {name: third_main_transaction_no, type: keyword}
        third_sub_transaction_no: {name: third_sub_transaction_no, type: keyword}
        remark: {name: remark, type: text}
        create_time: {name: create_time, type: date, format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSSZ||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ssZ||epoch_millis"}
        update_time: {name: update_time, type: date, format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSSZ||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ssZ||epoch_millis"}
