apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-adapter-config
  namespace: es
data:
  es.yml: |
    dataSourceKey: defaultDS
    destination: example
    groupId: g1
    esMapping:
      _index: mysql-index
      _type: _doc
      id: id
      sql: "SELECT * FROM pt-member.mem_account_change"
