apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-adapter
  namespace: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canal-adapter
  template:
    metadata:
      labels:
        app: canal-adapter
    spec:
      containers:
      - name: canal-adapter
        image: harbor.pttech.cc/canal/canal-adapter:1.1.8
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: canal-adapter-config-volume
          mountPath: /opt/canal-adapter/conf/application.yml
          subPath: application.yml
        - name: canal-adapter-es-volume
          mountPath: /opt/canal-adapter/conf/es7/pt-member.yml
          subPath: pt-member.yml
      volumes:
      - name: canal-adapter-config-volume
        configMap:
          name: canal-adapter-config
      - name: canal-adapter-es-volume
        configMap:
          name: canal-adapter-config-es