apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsdd-logs-pvc
  namespace: tf
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi