apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: es
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      securityContext:
        fsGroup: 0
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.2
        args: ["-e", "-c", "/usr/share/filebeat/filebeat.yml"]
        env:
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: password
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: varlogcontainers
          mountPath: /var/log/pods/
          readOnly: true
        - name: varlibkubelet
          mountPath: /var/lib/kubelet
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlogcontainers
        hostPath:
          path: /var/log/pods/
      - name: varlibkubelet
        hostPath:
          path: /var/lib/kubelet
