db:
  ip: 172.31.24.41
# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /opt/javaserver/uploadPath）
  profile: /opt/javaserver/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  port: 8074
  servlet:
    encoding:
      enabled: false
    context-path: /apid
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
  file:
    name: front.out


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'

#配置admin监控访问实例时需要的token
admin:
  header:
    auth:
      name: "monitor"
      password: "qq134567"


# Spring配置
spring:
  application:
    ## 注册服务名
    name: cash-front
  ## spring boot admin
  boot:
    admin:
      client:
        #api-path:
        url: http://127.0.0.1:8000
        #api-path: http://ironldy.g9008.com
        instance:
          prefer-ip: true # 使用ip注册进来

  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://172.31.24.41:3306/zc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: zc
        password: C!rlO6V6NWimYw4f
#        username: root
#        password: root
      # 从库数据源
#      slave:
#        # 从数据源开关/默认关闭
#        enabled: true
#        url: jdbc:mysql://46.149.202.219:3306/cash_slave?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
#        username: cash_slave
#        password: cYcpnCdB8JmbzTtP
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  100MB
      # 设置总上传的文件大小
      max-request-size:  200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 172.31.24.41
    # 端口，默认为6379
    #port: 9097
    port: 6379
    # 数据库索引
    database: 9
    # 密码
    password: '!yHahw2$4GWYOR7m'
#    password:
    # 连接超时时间
    timeout: 60s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mail:
    host: smtp.gmail.com
    password: bwpnfsuptcpjyumm
    port: 465
    username: ruiyou1000@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  jackson:
    serialization:
      indent-output: true
# token配置
token:
  # 是否允许账户多终端同时登录（true允许 false不允许）
  soloLogin: false
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 600

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /client/*,/mobile/*


# Minio配置
minio:
  url: https://img.zctz.net
  accessKey: YQ8RXzTBv76Se4LL5SpK
  secretKey: CKLoLo7Y0NyqJtniTZBPzTLVIcJO0ipQZRoDHITd
  bucketName: cash


# 腾讯云短信配置
# tx:
#   secretId: xxxxxxxxxx
#   secretKey: xxxxxxxxxx
#   templateId: 1963032
#   signName: test
#   sdkAppId: 1400863921

#chatgpt:
#  token: xxxxxxxxxsk-proj-xxxxxxxxxx
chatgpt:
  #token: xxxxxxxxxx
  token: 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
  chat-model: gpt-3.5-turbo-1106 #可选
  #proxy-host: 127.0.0.1 #需要代理时必填
  #proxy-port: 7890 #需要代理时必填
  #  model: text-davinci-003 #可选 model可填可不填，默认即text-davinci-003
  #  retries: 10 #可选，指的是当chatgpt第一次请求回答失败时，重新请求的次数（增加该参数的原因是因为大量访问的原因，在某一个时刻，chatgpt服务将处于无法访问的情况，不填的默认值为5）
  session-expiration-time: 30 #（单位（min））为这个会话在多久不访问后被销毁，这个值不填的时候，即表示所有问答处于同一个会话之下，相同user的会话永不销毁（增加请求消耗）
  #  base-url: https://apps.ichati.cn/1d6f32f8-b59d-46f8-85e9-7d434bxxxxxx/ #可选，默认为https://api.openai.com/
  #  token-strategy-impl: io.github.asleepyfish.strategy.DefaultTokenStrategy #可选，默认为RandomTokenStrategy（随机）
  #  alter-tokens: #可选，备选tokens，可以和token-strategy-impl结合，每次请求按策略分配token
  #    - sk-xxx2
  #    - sk-xxx3



inta:
  userName: Russia_1
  password: Russia_1@987
  url: http://intapi.253.com/send/json