version: '3.8'

services:
  mysql:
    container_name: mysql_percona
    user: "1001:1001"
    restart: always
    image: percona:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sa3dd3SLKJDf
      MYSQL_DATABASE: zhijia
      MYSQL_CMD_EXTRA_OPTS: "--authentication-policy=mysql_native_password,*,*"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /etc/localtime:/etc/localtime


