apiVersion: v1
kind: ConfigMap
metadata:
  name: mvn-settings
  labels:
    app: jenkins-server
  namespace: devops

data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <!-- 本地仓库目录 -->
    <localRepository>/var/jenkins_home/repository</localRepository>

    <!-- Maven的交互模式 -->
    <interactiveMode>true</interactiveMode>
    <offline>false</offline>

    <!-- 插件组 -->
    <pluginGroups>
      <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
    </pluginGroups>

    <!-- 配置Profile -->
    <profiles>
      <profile>
          <id>sonar</id>
          <activation>
              <activeByDefault>true</activeByDefault>
          </activation>
          <properties>
              <!-- SonarQube服务器地址 -->
              <sonar.host.url>http://sonarqube.sonarqube:9000</sonar.host.url>
          </properties>
      </profile>
    </profiles>

    <!-- 配置镜像 -->
    <mirrors>
      <mirror>
        <id>mirrorId</id>
        <mirrorOf>*</mirrorOf>
        <name>Human Readable Name for this Mirror</name>
        <url>https://nexus3.1fx.me/repository/maven-public/</url>
      </mirror>
    </mirrors>
    </settings>
