apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mav-pvc
  namespace: devops
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi