apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zyh-h5
  namespace: zyh
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: web.jgread.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zyh-h5
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zyh-admin
  namespace: zyh
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: admin.jgread.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zyh-admin
            port:
              number: 80
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-zyh-ingress
  namespace: zyh
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: api.jgread.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zyh-tsdd-svc
            port:
              number: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zyh-wss-ingress
  namespace: zyh
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: wss.jgread.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zyh-wk-svc
            port:
              number: 5200