apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
