apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-admin-modules-system
  namespace: pt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pt-admin-modules-system
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pt-admin-modules-system
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: JAVA_OPTS
              value: -Xms128m -Xmx512m
            - name: NACOS_ADDR
              value: nacos-server-svc.pt.svc.cluster.local
          image: harbor.pttech.cc/dev/pt-admin-modules-system:c69ece0
          imagePullPolicy: Always
          name: pt-admin-modules-system
          ports:
            - containerPort: 9211
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: geoip-volume
              mountPath: /usr/local/etc/redis/GeoLite2-City.mmdb
              subPath: GeoLite2-City.mmdb
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: geoip-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: pt-admin-modules-system-svc
  namespace: pt
spec:
  ports:
    - nodePort: 39211
      port: 9211
      protocol: TCP
      targetPort: 9211
  selector:
    app: pt-admin-modules-system
  type: NodePort
