apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoip-pv
  namespace: pt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/geoip  # 主机上的路径
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoip-pvc
  namespace: pt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
