apiVersion: batch/v1
kind: Job
metadata:
  name: agent-loader
  namespace: pt-pre
spec:
  template:
    spec:
      containers:
        - name: loader
          image: alpine:3.19
          command: ["sh", "-c"]
          args:
            - |
              apk update && apk add --no-cache bash curl tar && \
              wget -O /tmp/agent.tgz https://archive.apache.org/dist/skywalking/java-agent/9.4.0/apache-skywalking-java-agent-9.4.0.tgz && \
              tar xf  /tmp/agent.tgz -C /mnt/agent
          volumeMounts:
            - name: skywalking-agent
              mountPath: /mnt/agent
      restartPolicy: Never
      volumes:
        - name: skywalking-agent
          persistentVolumeClaim:
            claimName: skywalking-agent-pvc
